CREATE TABLE block_placed (

  x NUMERIC NOT NULL,
  y NUMERIC NOT NULL,
  z NUMERIC NOT NULL,
  material NUMERIC NOT NULL,
  time TIMESTAMP NOT NULL,
  block_id BIGINT UNIQUE AUTO_INCREMENT,
  is_destroyed BOOL NOT NULL,

  PRIMARY KEY (x,y,z),
  INDEX (block_id)
);